@startuml
class Salvajes {
    - todosLosPokemon : List<PokemonBase>
    - zonaBase : ZonaBase
    - tiposZona : Type[]
    - Awake() : void
    + Inicializar() : void
    + GenerarPokemonSalvaje(nivelMedioEquipo:int) : Pokemon
}
MonoBehaviour <|-- Salvajes
@enduml
