@startuml
class HPBar {
    + slider : Slider
    + gradient : Gradient
    + hpBar : Image
    + SetMaxHP(hp:int) : void
    + setHP(hp:int) : void
    + animacionHP(newHP:int) : IEnumerator
}
MonoBehaviour <|-- HPBar
@enduml
