@startuml
class SistemaCombate {
    + pkmnJugador : PkmnCombate
    - pkmnJugadorHUD : CombateHUD
    + pkmnEnemigo : PkmnCombate
    - pkmnEnemigoHUD : CombateHUD
    - Atk1 : Button
    - Atk2 : Button
    - partida : ControladorPartida
    - AtkType : Type
    - isAttaking : bool
    - isFinish : bool
    + IniciarCombate(controller:ControladorPartida) : void
    + SetupBattle() : void
    + GetAtkType() : void
    - TerminarCombate() : IEnumerator
    + {static} StringToType(tipo:string) : Type
    - TurnoJugador() : IEnumerator
    - TurnoEnemigo() : IEnumerator
    + DoDmg(tipo:Type, atacante:Pokemon, defensor:Pokemon) : bool
    + EnemyAtk() : Type
    - {static} <<readonly>> tablaTipos : Dictionary<Type, Dictionary<Type, float>>
    + {static} CalcularEfectividad(ataque:Type, defensa1:Type, defensa2:Type) : float
    - {static} GetMultiplier(ataque:Type, defensa:Type) : float
}
MonoBehaviour <|-- SistemaCombate
@enduml
