@startuml
class CarruselImagenes {
    + imagenes : RectTransform[]
    + duracionAnimacion : float
    - zonasDisponibles : ZonaBase[]
    - spritesZonasDisponibles : List<Sprite>
    - zonasLegendariasDisponibles : ZonaBase[]
    - spriteZonasLegendariasDisponibles : List<Sprite>
    + zonaInicial : ZonaBase
    - indiceActual : int
    - desplazamiento : float
    - zonaActual : ZonaBase
    - isCambiando : bool = false
    - ultimaFueLegendaria : bool = false
    - Start() : void
    - CargarImagenes() : void
    - AsignarImagenesIniciales() : void
    + AvanzarCarrusel(onFinish:System.Action) : void
    - AnimarCarrusel(imagenActual:RectTransform, imagenNueva:RectTransform, onFinish:System.Action) : IEnumerator
}
MonoBehaviour <|-- CarruselImagenes
@enduml
