@startuml
class InterfazEquipo {
    - equipo : Equipo
    - botones : GameObject[]
    - botonesOpcion : GameObject
    + PokemonSeleccionado : Pokemon <<get>>
    + Equipo : Equipo <<get>>
    + indiceSeleccionado : int
    - modoIntercambio : bool = false
    - indiceIntercambio : int
    - Start() : void
    - Update() : void
    + IniciarIntercambio() : void
    + SeleccionarPokemon(indice:int) : void
    + LimpiarSeleccion() : void
    + ActualizarInterfaz() : void
}
MonoBehaviour <|-- InterfazEquipo
@enduml
