@startuml
class SeleccionDePersonajes {
    - TrainersButtons : Button[]
    - PokemonButtons : Button[]
    - controladorPartida : ControladorPartida
    - botonAceptar : Button
    - audioManager : AudioManager
    - trainerSeleccionado : int
    - pokemonSeleccionado : int
    - <<readonly>> numerosPokemon : int[]
    - <<readonly>> nombresTrainers : string[]
    - Start() : void
    - SeleccionarTrainer(index:int) : void
    - SeleccionarPokemon(index:int) : void
    - ActualizarBotonAceptar() : void
    - ConfirmarSeleccion() : void
    - ActualizarColoresTrainers() : void
    - ActualizarColoresPokemons() : void
}
MonoBehaviour <|-- SeleccionDePersonajes
@enduml
