@startuml
class ControldorInterfaz {
    - carruselImagenes : CarruselImagenes
    - cambiadorSprites : CambiadorSprites
    - controladorPartida : ControladorPartida
    + sistemaMenu : SistemaMenu
    + zonaActual : ZonaBase
    - audioManager : AudioManager
    - explorado : bool = false
    - animacionesPendientes : int = 0
    - inicio : bool = true
    + avanzarButton : Button
    + explorarButton : Button
    + equipoButton : Button
    + PCButton : Button
    + btnDatos : Button
    + btnEliminarEquipo : Button
    + btnVolverDatos : Button
    + salirEquipoButton : Button
    + btnCambiarEquipo : Button
    + btnEliminarPC : Button
    + btnSalirPC : Button
    + btnCajaSiguiente : Button
    + btnCajaAnterior : Button
    + btnCambarConEquipoPC : Button
    + btnSacarPc : Button
    + btnMeterPC : Button
    + btnMostrarEquipo : Button
    + btnContinuar : Button
    + btnNuevaPartida : Button
    + huirButton : Button
    - Awake() : void
    - Start() : void
    - OnSalirPCButtonClick() : void
    - OnNuevaPartidaButtonClick() : void
    - OnContinuarButtonClick() : void
    - OnMostrarEquipoButtonClick() : void
    - OnMeterPCButtonClick() : void
    - OnSacarPCButtonClick() : void
    - OnCambiarConEquipoPCButtonClick() : void
    - OnCambiarEquipoButtonClick() : void
    - OnEliminarPCButtonClick() : void
    - OnEliminarEquipoButtonClick() : void
    - OnPCButtonClick() : void
    - OnCajaAnteriorButtonClick() : void
    - OnCajaSiguienteButtonClick() : void
    + OnHuirButtonClick() : void
    + OnAvanzarButtonClick() : void
    + OnAnimacionTerminada() : void
    + OnExplorarButtonClick() : void
    - IniciarCombateTrasAnimacion() : IEnumerator
    + OnEquipoButtonClick() : void
    + OnSalirEquipoButtonClick() : void
    + OnDatosButtonClick() : void
    + OnVolverDatosButtonClick() : void
    + BloquearAvanzarTemporalmente() : void
    - DesbloquearAvanzarTrasAnimacion() : IEnumerator
}
MonoBehaviour <|-- ControldorInterfaz
@enduml
