@startuml
class ControladorPartida {
    + interfaz : ControldorInterfaz
    - sistemaCombate : SistemaCombate
    - sistemaCaptura : SistemaCaptura
    - sistemaDatos : InterfazDatosPokemon
    - sistemaEquipo : InterfazEquipo
    - sistemaMenu : SistemaMenu
    - sistemaPC : PC
    - equipo : Equipo
    - audioManager : AudioManager
    - interfazExploracion : Canvas
    - mainCamera : Camera
    - interfazBatalla : Canvas
    - CamaraBatalla : Camera
    - interfazEquipo : Canvas
    - CamaraEquipo : Camera
    - interfazDatos : Canvas
    - CamaraDatos : Camera
    - CamaraPC : Camera
    - interfazPC : Canvas
    - CamaraMenuInicio : Camera
    - interfazMenuInicio : Canvas
    - interfazSeleccionPersonaje : Canvas
    - camaraSeleccionPersonaje : Camera
    + jugador : Player
    - zonaActual : GameObject
    - Start() : void
    - Awake() : void
    + MostrarMenuInicio() : void
    + IniciarCombate() : void
    + CurarPokemon() : void
    + TerminarCombate() : void
    + TerminarCombate(pkmn:Pokemon) : void
    - ActivarExploracion(cambiarMusica:bool) : void
    + PantallaEquipo() : void
    + PantallaDatos() : void
    + SalirPantallaEquipo() : void
    + SalirPantallaDatos() : void
    + EliminarPokemonEquipo() : void
    + PantallaPC() : void
    + SalirPantallaPC() : void
    - ForzarPanelEquipoOculto() : IEnumerator
    + CambiarCaja(direccion:int) : void
    + EliminarPokemonPC() : void
    + CambiarPokemon() : void
    + CambiarPokemonPC() : void
    + SacarPokemonPC() : void
    + MostrarPanelEquipo() : void
    + MeterPokemonPC() : void
    - CambiarAudioListener(camaraActiva:Camera) : void
    + ContinuarPartida() : void
    + IniciarNuevaPartida(trainerName:string, pokemonIndex:int) : void
    + MostrarSeleccionDePersonaje() : void
}
MonoBehaviour <|-- ControladorPartida
@enduml
