@startuml
!include .\\ControladorPartida.puml
!include .\\ControldorInterfaz.puml
!include .\\Player.puml
!include .\\Pokeball.puml
!include .\\Trainer.puml
!include .\\TrainerManager.puml
!include .\\ZonaBase.puml
@enduml
