@startuml
class PkmnCombate {
    + isEnemy : bool
    - audioManager : AudioManager
    + objetoPkmn : GameObject
    + shadow : SpriteRenderer
    + Pkmn : Pokemon <<get>> <<set>>
    - PosInicial : Vector3
    - colorInicial : Color
    - <<readonly>> sombraOffset : Vector3
    - Awake() : void
    + Setup(pkmn:Pokemon) : void
    + GetSprite() : Sprite
    + AnimacionEntrada() : void
    + AnimacionAtaque() : void
    + AnimacionGolpe() : void
    + AnimacionDerrota() : void
    + ReiniciarEstado() : void
}
MonoBehaviour <|-- PkmnCombate
@enduml
