@startuml
class ControldorInterfaz {
    - carruselImagenes : CarruselImagenes
    - cambiadorSpritesTrainer : CambiadorSpritesTrainer
    - cambiadorSpritesPkmn : CambiadorSpritesPkmn
    - controladorPartida : ControladorPartida
    - explorado : bool = false
    + avanzarButton : Button
    + explorarButton : Button
    - Awake() : void
    - Start() : void
    + OnAvanzarButtonClick() : void
    + OnExplorarButtonClick() : void
}
MonoBehaviour <|-- ControldorInterfaz
@enduml
