@startuml
class PokemonBase {
    - num : int
    - nombre : string
    - tipo1 : Type
    - tipo2 : Type
    - idle : Sprite
    - idleShiny : Sprite
    - explorar : Sprite
    - explorarShiny : Sprite
    - andar : Sprite[]
    - andarShiny : Sprite[]
    - hp : int
    - atk : int
    - def : int
    - lvlEvo : int
    - evolucion : PokemonBase
    - minLvl : int
    - ratioCaptura : int
    - tipoExp : string
    + Tipo1 : Type <<get>>
    + Tipo2 : Type <<get>>
    + Evolucion : PokemonBase <<get>>
    + Nombre : string <<get>>
    + Num : int <<get>>
    + Def : int <<get>>
    + Atk : int <<get>>
    + Hp : int <<get>>
    + LvlEvo : int <<get>>
    + MinLvl : int <<get>>
    + SpriteTipo1 : Sprite
    + SpriteTipo2 : Sprite
    + SpriteIdle : Sprite <<get>>
    + SpriteIdleShiny : Sprite <<get>>
    + SpriteExploracion : Sprite <<get>>
    + SpriteExploracionShiny : Sprite <<get>>
    + SpritesAndar : Sprite[] <<get>>
    + SpritesAndarShiny : Sprite[] <<get>>
}
enum Type {
    None,
    Acero,
    Agua,
    Bicho,
    Dragon,
    Electrico,
    Fantasma,
    Fuego,
    Hada,
    Hielo,
    Lucha,
    Normal,
    Planta,
    Psiquico,
    Roca,
    Siniestro,
    Tierra,
    Veneno,
    Volador,
}
ScriptableObject <|-- PokemonBase
@enduml
