@startuml
class CambiadorSpritesPkmn {
    + isShiny : bool = false
    - walkRepetitions : int = 5
    + pokemonBackObject : GameObject
    - spriteRenderer : SpriteRenderer
    + pokemon : PokemonBase
    - currentFrame : int = 0
    - isWalking : bool = false
    - walkCounter : int = 0
    - Start() : void
    - SetIdle() : void
    + StartWalking() : void
    - WalkCoroutine() : IEnumerator
    + Search() : void
    - SearchCoroutine() : IEnumerator
}
MonoBehaviour <|-- CambiadorSpritesPkmn
@enduml
