@startuml
class CambiadorSpritesTrainer {
    + trainerName : string
    + walkRepetitions : int = 5
    + trainerGameObject : GameObject
    - spriteRenderer : SpriteRenderer
    - walkSprites : Sprite[]
    - idle : Sprite
    - search : Sprite
    - walkCoroutine : Coroutine
    - isWalking : bool = false
    - Start() : void
    - LoadSprites() : void
    - SetIdle() : void
    + StartWalking() : void
    - WalkAnimation() : IEnumerator
    - SetSearch() : IEnumerator
    + Search() : void
}
MonoBehaviour <|-- CambiadorSpritesTrainer
@enduml
